#!/usr/bin/env python
#
# Copyright 2014 wkhtmltopdf authors
#
# This file is part of wkhtmltopdf.
#
# wkhtmltopdf is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# wkhtmltopdf is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with wkhtmltopdf.  If not, see <http:#www.gnu.org/licenses/>.

CLEANUP_FILES_FOR = {
    'qt' : [
        # top-level files
        '.commit-template',
        '.gitattributes',
        '.hgignore',
        '.tag',
        'header.*',
        'LICENSE.PREVIEW.COMMERCIAL',
        # top-level directories
        'config.profiles/',
        'demos/',
        'dist/',
        'doc/',
        'examples/',
        'imports/',
        'templates/',
        'tests/',
        'translations/',
        'util/',
        # unused tools in bin/
        'bin/c*',
        'bin/e*',
        'bin/f*',
        'bin/p*',
        'bin/setcepaths.bat',
        # fonts in lib/
        'lib/fonts',
        # unused mkspecs
        'mkspecs/aix*',
        'mkspecs/blackberry*',
        'mkspecs/hpux*',
        'mkspecs/irix*',
        'mkspecs/q*',
        'mkspecs/s*',
        'mkspecs/t*',
        'mkspecs/wince*',
        # unused tools
        'tools/tools.pro',
        'tools/activeqt/',
        'tools/assistant/',
        'tools/checksdk/',
        'tools/configure/',
        'tools/designer/',
        'tools/doxygen/',
        'tools/kmap2qmap/',
        'tools/linguist/',
        'tools/macdeployqt/',
        'tools/makeqpf/',
        'tools/pixeltool/',
        'tools/porting/',
        'tools/qconfig/',
        'tools/qdbus/',
        'tools/qdoc3/',
        'tools/qev/',
        'tools/qmeegographicssystemhelper/',
        'tools/qml/',
        'tools/qmlplugindump/',
        'tools/qtconcurrent/',
        'tools/qtconfig/',
        'tools/qtestlib/',
        'tools/qttracereplay/',
        'tools/qvfb/',
        'tools/runonphone/',
        'tools/xmlpatterns/',
        'tools/xmlpatternsvalidator/',
        'tools/shared/deviceskin/',
        'tools/shared/findwidget/',
        'tools/shared/fontpanel/',
        'tools/shared/qtgradienteditor/',
        'tools/shared/qtpropertybrowser/',
        'tools/shared/qttoolbardialog/',
        # unused modules
        'src/activeqt',
        'src/dbus',
        'src/declarative',
        'src/gui/egl',
        'src/gui/embedded',
        'src/gui/s60framework',
        'src/gui/symbian/images',
        'src/imports',
        'src/multimedia',
        'src/opengl',
        'src/openvg',
        'src/phonon',
        'src/qt3support',
        'src/s60installs',
        'src/s60main',
        'src/script',
        'src/scripttools',
        'src/sql',
        'src/testlib',
        'src/tools/uic3',
        # unused plugins
        'src/plugins/accessible',
        'src/plugins/bearer',
        'src/plugins/decorations',
        'src/plugins/generic',
        'src/plugins/gfxdrivers',
        'src/plugins/graphicssystems',
        'src/plugins/iconengines',
        'src/plugins/imageformats/gif',
        'src/plugins/imageformats/jpeg',
        'src/plugins/imageformats/mng',
        'src/plugins/imageformats/svg',
        'src/plugins/imageformats/tga',
        'src/plugins/imageformats/tiff',
        'src/plugins/inputmethods',
        'src/plugins/kbddrivers',
        'src/plugins/mousedrivers',
        'src/plugins/phonon',
        'src/plugins/platforms/blackberry',
        'src/plugins/platforms/cocoa',
        'src/plugins/platforms/directfb',
        'src/plugins/platforms/eglconvenience',
        'src/plugins/platforms/eglfs',
        'src/plugins/platforms/externalplugin.pri',
        'src/plugins/platforms/fb_base',
        'src/plugins/platforms/fontdatabases/coretext',
        'src/plugins/platforms/glxconvenience',
        'src/plugins/platforms/openkode',
        'src/plugins/platforms/platforms.pro',
        'src/plugins/platforms/qvfb',
        'src/plugins/platforms/uikit',
        'src/plugins/platforms/vnc',
        'src/plugins/platforms/wayland',
        'src/plugins/platforms/xcb',
        'src/plugins/platforms/xlib',
        'src/plugins/qmltooling',
        # 3rd party code
        'src/3rdparty/.gitattributes',
        'src/3rdparty/libgq.pri',
        'src/3rdparty/libmng.pri',
        'src/3rdparty/libtiff.pri',
        'src/3rdparty/ce-compat/',
        'src/3rdparty/clucene/',
        'src/3rdparty/fonts/',
        'src/3rdparty/freetype/',
        'src/3rdparty/javascriptcore/',
        'src/3rdparty/libgq/',
        'src/3rdparty/libmng/',
        'src/3rdparty/libtiff/',
        'src/3rdparty/patches/',
        'src/3rdparty/phonon/',
        'src/3rdparty/pixman/',
        'src/3rdparty/powervr/',
        'src/3rdparty/ptmalloc/',
        'src/3rdparty/s60/',
        'src/3rdparty/wayland/',
        'src/3rdparty/webkit/'
    ],
    
    'webkit' : [
        # top-level folders
        'LayoutTests/',
        'PerformanceTests/',
        'ManualTests/',
        'Websites/',
        'Examples/',
        'WebKit.xcworkspace/',
        # changelogs
        'ChangeLog',
        'ChangeLog-2012-05-22',
        'Source/JavaScriptCore/ChangeLog',
        'Source/JavaScriptCore/ChangeLog-2002-12-03',
        'Source/JavaScriptCore/ChangeLog-2003-10-25',
        'Source/JavaScriptCore/ChangeLog-2007-10-14',
        'Source/JavaScriptCore/ChangeLog-2008-08-10',
        'Source/JavaScriptCore/ChangeLog-2009-06-16',
        'Source/JavaScriptCore/ChangeLog-2010-05-24',
        'Source/JavaScriptCore/ChangeLog-2011-02-16',
        'Source/JavaScriptCore/ChangeLog-2012-05-22',
        'Source/JavaScriptCore/ChangeLog-2012-10-02',
        'Source/Platform/ChangeLog',
        'Source/ThirdParty/ANGLE/ChangeLog',
        'Source/ThirdParty/ChangeLog',
        'Source/WebCore/ChangeLog',
        'Source/WebCore/ChangeLog-2002-12-03',
        'Source/WebCore/ChangeLog-2003-10-25',
        'Source/WebCore/ChangeLog-2005-08-23',
        'Source/WebCore/ChangeLog-2005-12-19',
        'Source/WebCore/ChangeLog-2006-05-10',
        'Source/WebCore/ChangeLog-2006-12-31',
        'Source/WebCore/ChangeLog-2007-10-14',
        'Source/WebCore/ChangeLog-2008-08-10',
        'Source/WebCore/ChangeLog-2009-06-16',
        'Source/WebCore/ChangeLog-2010-01-29',
        'Source/WebCore/ChangeLog-2010-05-24',
        'Source/WebCore/ChangeLog-2010-12-06',
        'Source/WebCore/ChangeLog-2011-02-16',
        'Source/WebCore/ChangeLog-2011-06-04',
        'Source/WebCore/ChangeLog-2011-10-19',
        'Source/WebCore/ChangeLog-2012-05-22',
        'Source/WebCore/ChangeLog-2012-10-02',
        'Source/WebKit/blackberry/ChangeLog',
        'Source/WebKit/cf/ChangeLog',
        'Source/WebKit/ChangeLog',
        'Source/WebKit/chromium/ChangeLog',
        'Source/WebKit/chromium/ChangeLog-2011-02-16',
        'Source/WebKit/chromium/ChangeLog-2012-05-22',
        'Source/WebKit/chromium/ChangeLog-2012-10-02',
        'Source/WebKit/efl/ChangeLog',
        'Source/WebKit/gtk/ChangeLog',
        'Source/WebKit/gtk/ChangeLog-2012-05-22',
        'Source/WebKit/gtk/po/ChangeLog',
        'Source/WebKit/mac/ChangeLog',
        'Source/WebKit/mac/ChangeLog-2002-12-03',
        'Source/WebKit/mac/ChangeLog-2006-02-09',
        'Source/WebKit/mac/ChangeLog-2007-10-14',
        'Source/WebKit/mac/ChangeLog-2010-01-29',
        'Source/WebKit/mac/ChangeLog-2012-10-02',
        'Source/WebKit/qt/ChangeLog',
        'Source/WebKit/qt/ChangeLog-2011-02-16',
        'Source/WebKit/win/ChangeLog',
        'Source/WebKit/win/ChangeLog-2009-06-16',
        'Source/WebKit/wince/ChangeLog',
        'Source/WebKit/wx/ChangeLog',
        'Source/WebKit2/ChangeLog',
        'Source/WebKit2/ChangeLog-2011-02-16',
        'Source/WebKit2/ChangeLog-2011-06-04',
        'Source/WebKit2/ChangeLog-2012-05-22',
        'Source/WebKit2/ChangeLog-2012-10-02',
        'Source/WTF/ChangeLog',
        'Tools/ChangeLog',
        'Tools/ChangeLog-2009-06-16',
        'Tools/ChangeLog-2010-05-24',
        'Tools/ChangeLog-2011-02-16',
        'Tools/ChangeLog-2012-05-22',
        'Tools/ChangeLog-2012-10-02',
        'Tools/iExploder/iexploder-1.7.2/ChangeLog.txt',
        'WebKitLibraries/ChangeLog',
        # unused tools
        'Tools/.gitattributes',
        'Tools/.gitignore',
        'Tools/BuildSlaveSupport',
        'Tools/clang',
        'Tools/CLWrapper',
        'Tools/CMakeLists.txt',
        'Tools/CodeCoverage',
        'Tools/CSSTestSuiteHarness',
        'Tools/CygwinDownloader',
        'Tools/DumpRenderTree',
        'Tools/efl',
        'Tools/EWebLauncher',
        'Tools/EWSTools',
        'Tools/gdb',
        'Tools/GNUmakefile.am',
        'Tools/gtk',
        'Tools/GtkLauncher',
        'Tools/iExploder',
        'Tools/jhbuild',
        'Tools/list',
        'Tools/lldb',
        'Tools/Makefile',
        'Tools/mangleme',
        'Tools/MIDLWrapper',
        'Tools/MiniBrowser',
        'Tools/QtTestBrowser',
        'Tools/QueueStatusServer',
        'Tools/RebaselineQueueServer',
        'Tools/record-memory-win',
        'Tools/Scripts/webkitpy',
        'Tools/TestResultServer',
        'Tools/TestWebKitAPI',
        'Tools/Tools.pro',
        'Tools/vcbin',
        'Tools/waf',
        'Tools/WebKitLauncher',
        'Tools/WebKitLauncherWin',
        'Tools/WebKitTestRunner',
        'Tools/win',
        'Tools/WinCELauncher',
        'Tools/WinLauncher',
        'Tools/wx',
        # unused source
        'Source/autotools',
        'Source/cmake',
        'Source/JavaScriptCore/API/tests',
        'Source/JavaScriptCore/icu',
        'Source/JavaScriptCore/tests',
        'Source/Platform',
        'Source/WTF/icu',
        'Source/WTF/wtf/blackberry',
        'Source/WTF/wtf/chromium',
        'Source/WTF/wtf/efl',
        'Source/WTF/wtf/gtk',
        'Source/WTF/wtf/wince',
        'Source/WTF/wtf/wx',
        'Source/WebCore/icu',
        'Source/WebCore/editing/blackberry',
        'Source/WebCore/history/blackberry',
        'Source/WebCore/loader/blackberry',
        'Source/WebCore/page/blackberry',
        'Source/WebCore/platform/blackberry',
        'Source/WebCore/platform/graphics/blackberry',
        'Source/WebCore/platform/graphics/filters/blackberry',
        'Source/WebCore/platform/image-decoders/blackberry',
        'Source/WebCore/platform/mediastream/blackberry',
        'Source/WebCore/platform/network/blackberry',
        'Source/WebCore/platform/text/blackberry',
        'Source/WebCore/plugins/blackberry',
        'Source/WebCore/Resources/blackberry',
        'Source/WebCore/accessibility/chromium',
        'Source/WebCore/editing/chromium',
        'Source/WebCore/loader/chromium',
        'Source/WebCore/Modules/filesystem/chromium',
        'Source/WebCore/Modules/webdatabase/chromium',
        'Source/WebCore/page/chromium',
        'Source/WebCore/page/scrolling/chromium',
        'Source/WebCore/platform/audio/chromium',
        'Source/WebCore/platform/chromium',
        'Source/WebCore/platform/graphics/chromium',
        'Source/WebCore/platform/mediastream/chromium',
        'Source/WebCore/platform/network/chromium',
        'Source/WebCore/platform/sql/chromium',
        'Source/WebCore/platform/text/chromium',
        'Source/WebCore/plugins/chromium',
        'Source/WebCore/storage/chromium',
        'Source/WebCore/bindings/v8',
        'Source/WebCore/testing/v8',
        'Source/WebCore/editing/gtk',
        'Source/WebCore/page/gtk',
        'Source/WebCore/platform/audio/gtk',
        'Source/WebCore/platform/graphics/gtk',
        'Source/WebCore/platform/gtk',
        'Source/WebCore/platform/network/gtk',
        'Source/WebCore/platform/text/gtk',
        'Source/WebCore/platform/wx/wxcode/gtk',
        'Source/WebCore/plugins/gtk',
        'Source/WebCore/loader/icon/wince',
        'Source/WebCore/page/wince',
        'Source/WebCore/platform/graphics/wince',
        'Source/WebCore/platform/text/wince',
        'Source/WebCore/platform/wince',
        'Source/WebCore/storage/wince',
        'Source/WebCore/page/efl',
        'Source/WebCore/platform/audio/efl',
        'Source/WebCore/platform/efl',
        'Source/WebCore/platform/graphics/efl',
        'Source/WebCore/platform/network/efl',
        'Source/WebCore/platform/text/efl',
        'Source/WebCore/plugins/efl',
        'Source/WebCore/accessibility/wx',
        'Source/WebCore/editing/wx',
        'Source/WebCore/page/wx',
        'Source/WebCore/platform/graphics/wx',
        'Source/WebCore/platform/image-decoders/wx',
        'Source/WebCore/platform/wx',
        'Source/WebCore/plugins/wx',
        'Source/WebKit/blackberry',
        'Source/WebKit/chromium',
        'Source/WebKit/gtk',
        'Source/WebKit/efl',
        'Source/WebKit/wince',
        'Source/WebKit/wx',
        'Source/WebKit2',
    ]
}

import os, sys

if not len(sys.argv) == 2:
    print "Usage: %s [%s]" % (sys.argv[0], '|'.join(list(CLEANUP_FILES_FOR.keys())))
    sys.exit(1)

for item in CLEANUP_FILES_FOR[sys.argv[1]]:
    os.system('git rm -fr %s' % item)

os.system('git commit -a -m "apply subtree_cleanup"')
